version: "3.8"


services:
  postgres:
    image: postgres:15-alpine
    container_name: units_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


  nginx_proxy:
    image: nginx:1.13-alpine
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./docker_config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker_config/certs:/certs"
      - "./microservices/units-backend/static:/static"
      - "./microservices/units-backend/media:/media"
      - "./microservices/units-frontend/dist/Units/browser:/usr/share/nginx/html"

  units_backend:
    container_name: units_backend
    build:
      context: ./docker_config/python_config
    working_dir: /home/python/app
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
    - "./microservices/units-backend:/home/python/app"
    - "./docker_config/python_config/deploy_commands.sh:/deploy_commands.sh"
    - "./logs:/logs"
    command: 
       - /bin/bash
       - -c
       - |
        echo "Starting django server ..."
        /deploy_commands.sh
    env_file:
      - .env

  units_finance:
    container_name: units_finance
    build:
      context: ./microservices/units-finance
    working_dir: /home/python/app
    depends_on:
      - postgres
    ports:
      - 8001:8001
    volumes:
    - "./microservices/units-finance:/home/python/app"
    - "./logs:/logs"
    command:
       - /bin/bash
       - -c
       - |
        echo "Starting finance django server ..."
        /home/python/app/deploy_commands.sh
    env_file:
      - .env

  units_frontend:
    container_name: units_frontend
    image: nginx:1.13-alpine
    ports:
      - "8002:80"
    volumes:
      - ./microservices/units-frontend/dist/Units/browser:/usr/share/nginx/html
    environment:
      API_URL: ${API_URL}

volumes:
  postgres_data:
